### PR TITLE
Increment quasar version to v53.0.0

### PR DESCRIPTION
**Pull request by alissapajer**

### CODE REVIEW

**Comment by alissapajer** [comment]
Will get us in line with https://github.com/slamdata/slamdata-backend/pull/430

**Comment by djspiewak** [comment]
@alissapajer Wasn't there an automated PR which did this?

**Comment by alissapajer** [comment]
@djspiewak the automated PRs don't work because of the license/cla.

**Comment by djspiewak** [comment]
@alissapajer What do you mean they don't work? They can still be merged.

**Comment by jsantos17** [comment]
@alissapajer 

I'll check this soon since I'll need to do some manual testing before merging this. Related issue:

https://app.clubhouse.io/data/story/565/verify-quasar-s3-loads-into-slamdata-backend-in-the-travis-build

**Pull request merged**
